name = "SandboxMCPRepl"
uuid = "a01f8ab4-3772-46a4-8f25-b289fd6fcd4a"
version = "0.1.0"
authors = ["Nathan Zimmerberg <nzimmerberg@gmail.com>"]

[workspace]
projects = ["test"]

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
ModelContextProtocol = "c58f755f-f2a7-4f48-bf29-4e9659b78499"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Sandbox = "9307e30f-c43e-9ca7-d17c-c2dc59df670d"

[compat]
ModelContextProtocol = "0.4"
Sandbox = "2.1"
julia = "1.12"

[apps.sandbox-mcp-repl]
